spring:
  application:
    name: academic-api

  datasource:
    url: jdbc:postgresql://localhost:5439/academic_optimization_db
    username: academic_user
    password: academic_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  name: Academic Optimization Platform
  company: TRIA Company